name: nightly-tests
on: [push]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy Builder
        uses: actions/checkout@v2
        with:
          path: builder
          persist-credentials: false

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/builder:/builder unifyai/ivy-builder:latest python3 -m pytest ivy_builder_tests/
